### ISSUE TITLE
dont reduce the size of the frame

### ISSUE THREAD

**Issue by d1snin** [EmeraldSnorlax/website#2]
I would recommend not to reduce the size of the frame when someone copies the key
![epic](https://user-images.githubusercontent.com/68169685/114278836-4d43c600-9a3a-11eb-8bba-ebf7c5ecca60.png)

**Comment by EmeraldSnorlax** [comment]
this is fixed by https://github.com/EmeraldSnorlax/website/commit/1e5f83111ea524eb273dcbbffc5d9df0dc9d3ef4
